name: Github Actions Deploy
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: SamKirkland/webdeploy@v1
        with:
          target-server: ${{ secrets.SERVER_IP }}
          ssh-port: ${{ secrets.SSH_PORT }}
          remote-user: ${{ secrets.USERNAME }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: ${{ secrets.DESTINATION_PATH }}
